### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information)

### ISSUE THREAD

**Issue by pecasdev** [lzm0/cronify#73]
![image](https://user-images.githubusercontent.com/33271004/227997067-e0103724-fc5b-485a-ad76-e0dc0a489bf9.png)

Hey Zimo, I was using cronify today and got the attached error. Just thought you should know. My input was the default "everyday at 9am".

**Comment by lzm0** [comment]
Hey Peter, thanks for the issue. I have fixed the issue, and the changes are deployed!

**Comment by pecasdev** [comment]
Hey again, I think the error is back
